### ISSUE TITLE
Error with Typo3 11 and PHP 8

### ISSUE THREAD

**Issue by tomashavner** [b13/justincase#13]
Hi,

Line 45 in /typo3conf/ext/justincase/src/Middleware/LowerCaseUri.php generates a PHP Warning in Typo3.11.5.16 and PHP 8: Undefined array key. 
$doRedirect = (bool)$site->getConfiguration()['settings']['redirectOnUpperCase'] ?? false; 
should be: 
$doRedirect = (bool)($site->getConfiguration()['settings']['redirectOnUpperCase'] ?? false);

Kind regards

Tomas

**Comment by bmack** [comment]
Solved in latest main branch. Will be shipped with the next release.
