### ISSUE TITLE
Error in the middleware configuration; there is no middleware named "typo3/cms-frontend/site-resolver"

### ISSUE THREAD

**Issue by weberdigital** [b13/justincase#20]
Currently in the middleware configuration, a non-existent TYPO3 middleware is mentioned: https://github.com/b13/justincase/blob/1.3.0/Configuration/RequestMiddlewares.php#L8 . The correct name of the middleware is `typo3/cms-frontend/site`.

I just installed this extension in a TYPO3 installation and because of this bug, the middleware didn't get a site object with the function call `$request->getAttribute('site')`. As a workaround I just patched the configuration file. This solved my issue.

During my research I found out, that this exact problem actually also once was present in TYPO3 itself: https://forge.typo3.org/issues/91846.

Thanks in advance for fixing this!

**Comment by achimfritz** [comment]
fixed with https://github.com/b13/justincase/pull/19/commits/12917e0173808801209c76683080dde7a0228b5e
