### ISSUE TITLE
ext:justincase causes a problem opposite to it's claim

### ISSUE THREAD

**Issue by infabo** [b13/justincase#4]
>  No matter what case your URL is, we'll hit it.

I have encountered a situation, where ext:justincase makes the opposite: it makes originally matching/working URLs suddenly not matching anymore.

Something is mentioned in the README already - but is misleading:

> Caveats
> If specific route enhancers check on camel-case (e.g. {order}/paymentForm/) this might lead to unexpected behaviours and 404 pages.

It fails even if the route-enhancer routePath casing is correct. **Any** route-argument which is **not fully lowercase** makes it break (404 exception).

See for more information: https://forge.typo3.org/issues/92565

**Comment by bmack** [comment]
@infabo I guess this happens if you have any URLs with a "slug" field or something similar that build non-lowercase URLs?

**Comment by infabo** [comment]
Yes. See link to forge issue.

**Comment by bmack** [comment]
Thank you. Any ideas / proposals on how to solve the use-case you described in the issue?

**Comment by infabo** [comment]
I would evaluate the incoming request has a matching route. Apply the lowercase stuff only if that fails.

**Comment by bmack** [comment]
Closing this one, looks good!
